// <auto-generated />
using System;
using AdminSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdminSystem.Api.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190416024513_addjsdOrder")]
    partial class addjsdOrder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AdminSystem.Domain.AggregatesModel.AttributeConfigAggregate.AttributeConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConfigDesc");

                    b.Property<string>("ConfigText");

                    b.Property<string>("ConfigValue");

                    b.Property<bool>("Enabled");

                    b.HasKey("Id");

                    b.ToTable("AttributeConfigs");
                });

            modelBuilder.Entity("AdminSystem.Domain.AggregatesModel.JsdOrderAggregate.JsdOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Amount");

                    b.Property<string>("CancelTureName");

                    b.Property<string>("CancelUserId");

                    b.Property<string>("CreateOrderMobile");

                    b.Property<string>("DeliveryUserId");

                    b.Property<string>("DeliveryUserName");

                    b.Property<string>("DeptCode");

                    b.Property<bool>("IsThisSystemChange");

                    b.Property<DateTime>("LastUpDate");

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.Property<string>("Mobile");

                    b.Property<string>("OprDate");

                    b.Property<string>("OrderCode");

                    b.Property<string>("Remark");

                    b.Property<string>("Status");

                    b.Property<string>("TrueName");

                    b.Property<string>("WeightCode");

                    b.HasKey("Id");

                    b.ToTable("JsdOrders");
                });

            modelBuilder.Entity("AdminSystem.Domain.AggregatesModel.JsdOrderAggregate.JsdOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<int?>("JsdOrderId");

                    b.Property<string>("MaterialCode");

                    b.Property<string>("OrderCode");

                    b.Property<int>("OrderId");

                    b.Property<string>("Price");

                    b.Property<string>("ProductCode");

                    b.Property<string>("ProductName");

                    b.Property<string>("Qty");

                    b.HasKey("Id");

                    b.HasIndex("JsdOrderId");

                    b.ToTable("JsdOrderItems");
                });

            modelBuilder.Entity("AdminSystem.Domain.AggregatesModel.UserAggregate.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeptCode");

                    b.Property<bool>("IsUseSms");

                    b.Property<string>("Phone");

                    b.Property<string>("SmsCode");

                    b.Property<DateTime>("SmsSendDatetime");

                    b.Property<string>("TrueName");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("AdminSystem.Domain.AggregatesModel.JsdOrderAggregate.JsdOrderItem", b =>
                {
                    b.HasOne("AdminSystem.Domain.AggregatesModel.JsdOrderAggregate.JsdOrder")
                        .WithMany("OrderItem")
                        .HasForeignKey("JsdOrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
